

#!/bin/sh

# make_FilterStudio.sh
# 
#
# Created by Topaz Labs on 11/14/16.

APP_NAME="Test Program"
APP_NAME_NO_SPACE="TestProgram"

#chmod -R 
#cp -R "${DEV_BUILD_DIR}${APP_NAME}"
chmod -R a+wr "${APP_NAME}".app
#cd /Projects/mycompany/myprogram/mac_setup

#tbd: put this back when we get the plugins working
#sudo chmod -R 755 TopazFilterStudio.plugin

#sudo chown -R $USER Topaz\ Filter\ Studio.app/Contents/Resources/

# set permissions for the app so it can read, write and execute
chmod -R 755 "$APP_NAME".app

# copy all the third party libs
cp /usr/local/lib_old/*.dylib /Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app/Contents/MacOS/
cp /usr/local/lib_old/*.*.dylib /Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app/Contents/MacOS/
cp /usr/local/lib_old/*.*.*.dylib /Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app/Contents/MacOS/
cp /usr/local/lib_old/*.*.*.*.dylib /Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app/Contents/MacOS/

# copy all the libs generated by the project itself (these are not thirdparty libs, these are Topaz dynamic libs)
cp -r /Projects/mycompany/myprogram/libs/osx/ "${APP_NAME}".app/Contents/MacOS/
cp ./Contents/Info.plist ./"${APP_NAME}".app/Contents/
#cp ./Contents/Resources/mainapp.icns ./"${APP_NAME}".app/Contents/Resources/
cp ./Contents/Resources/TestProgrambeta.icns ./"${APP_NAME}".app/Contents/Resources/
cp -R ./Contents/Resources/"${APP_NAME_NO_SPACE}".plugin ./"${APP_NAME}".app/Contents/Resources/
cp ./Contents/Resources/"${APP_NAME_NO_SPACE}".lrtemplate ./"${APP_NAME}".app/Contents/Resources/
cp ./Contents/Slider.qml ./"${APP_NAME}".app/Contents/Resources/qml/QtQuick/Controls/

# macdeployqt is going to essentially shuffle around some dirs and grab some necessary delis

cd ~/Qt/5.6/clang_64/bin/
~/Qt/5.6/clang_64/bin/macdeployqt /Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app -qmldir=/Projects/mycompany/myprogram/
~/Qt/5.6/clang_64/bin/macdeployqt /Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app -qmldir=/Projects/mycompany/myprogram/mac_setup/"${APP_NAME}".app/Contents/MacOS
cd /Projects/mycompany/myprogram/mac_setup/

mv "${APP_NAME}".app/Contents/MacOS/*.dylib "${APP_NAME}".app/Contents/Frameworks 
rm "${APP_NAME}".app/Contents/MacOS/*.a

cp -R qml_56/* "${APP_NAME}".app/Contents/MacOS

sudo chown -R $USER "${APP_NAME}".app/Contents/

# working
 sudo ruby ./fix_deps_lib3.rb ./"${APP_NAME}".app/Contents/Frameworks/
 sudo ruby ./fix_deps_lib3.rb ./"${APP_NAME}".app/Contents/MacOs/Test\ Program
 sudo ruby ./fix_deps.rb ./"${APP_NAME}".app
