

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindJasper.cmake")
# Global approach
set(Jasper_FOUND 1)
set(Jasper_VERSION "2.0.21")

find_package_handle_standard_args(Jasper REQUIRED_VARS
                                  Jasper_VERSION VERSION_VAR Jasper_VERSION)
mark_as_advanced(Jasper_FOUND Jasper_VERSION)


set(Jasper_INCLUDE_DIRS "/home/duck/.conan/data/jasper/2.0.21/_/_/package/37f81ce48f57e0ea6fafe8f25ce1a4e5702094ed/include")
set(Jasper_INCLUDE_DIR "/home/duck/.conan/data/jasper/2.0.21/_/_/package/37f81ce48f57e0ea6fafe8f25ce1a4e5702094ed/include")
set(Jasper_INCLUDES "/home/duck/.conan/data/jasper/2.0.21/_/_/package/37f81ce48f57e0ea6fafe8f25ce1a4e5702094ed/include")
set(Jasper_RES_DIRS )
set(Jasper_DEFINITIONS )
set(Jasper_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(Jasper_COMPILE_DEFINITIONS )
set(Jasper_COMPILE_OPTIONS_LIST "" "")
set(Jasper_COMPILE_OPTIONS_C "")
set(Jasper_COMPILE_OPTIONS_CXX "")
set(Jasper_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(Jasper_LIBRARIES "") # Will be filled later
set(Jasper_LIBS "") # Same as Jasper_LIBRARIES
set(Jasper_SYSTEM_LIBS m)
set(Jasper_FRAMEWORK_DIRS )
set(Jasper_FRAMEWORKS )
set(Jasper_FRAMEWORKS_FOUND "") # Will be filled later
set(Jasper_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(Jasper_FRAMEWORKS_FOUND "${Jasper_FRAMEWORKS}" "${Jasper_FRAMEWORK_DIRS}")

mark_as_advanced(Jasper_INCLUDE_DIRS
                 Jasper_INCLUDE_DIR
                 Jasper_INCLUDES
                 Jasper_DEFINITIONS
                 Jasper_LINKER_FLAGS_LIST
                 Jasper_COMPILE_DEFINITIONS
                 Jasper_COMPILE_OPTIONS_LIST
                 Jasper_LIBRARIES
                 Jasper_LIBS
                 Jasper_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to Jasper_LIBS and Jasper_LIBRARY_LIST
set(Jasper_LIBRARY_LIST jasper)
set(Jasper_LIB_DIRS "/home/duck/.conan/data/jasper/2.0.21/_/_/package/37f81ce48f57e0ea6fafe8f25ce1a4e5702094ed/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_Jasper_DEPENDENCIES "${Jasper_FRAMEWORKS_FOUND} ${Jasper_SYSTEM_LIBS} JPEG::JPEG")

conan_package_library_targets("${Jasper_LIBRARY_LIST}"  # libraries
                              "${Jasper_LIB_DIRS}"      # package_libdir
                              "${_Jasper_DEPENDENCIES}"  # deps
                              Jasper_LIBRARIES            # out_libraries
                              Jasper_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "Jasper")                                      # package_name

set(Jasper_LIBS ${Jasper_LIBRARIES})

foreach(_FRAMEWORK ${Jasper_FRAMEWORKS_FOUND})
    list(APPEND Jasper_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND Jasper_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${Jasper_SYSTEM_LIBS})
    list(APPEND Jasper_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND Jasper_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(Jasper_LIBRARIES_TARGETS "${Jasper_LIBRARIES_TARGETS};JPEG::JPEG")
set(Jasper_LIBRARIES "${Jasper_LIBRARIES};JPEG::JPEG")

set(CMAKE_MODULE_PATH "/home/duck/.conan/data/jasper/2.0.21/_/_/package/37f81ce48f57e0ea6fafe8f25ce1a4e5702094ed/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/duck/.conan/data/jasper/2.0.21/_/_/package/37f81ce48f57e0ea6fafe8f25ce1a4e5702094ed/" ${CMAKE_PREFIX_PATH})

foreach(_BUILD_MODULE_PATH ${Jasper_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Jasper::Jasper)
        add_library(Jasper::Jasper INTERFACE IMPORTED)
        if(Jasper_INCLUDE_DIRS)
            set_target_properties(Jasper::Jasper PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${Jasper_INCLUDE_DIRS}")
        endif()
        set_property(TARGET Jasper::Jasper PROPERTY INTERFACE_LINK_LIBRARIES
                     "${Jasper_LIBRARIES_TARGETS};${Jasper_LINKER_FLAGS_LIST}")
        set_property(TARGET Jasper::Jasper PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${Jasper_COMPILE_DEFINITIONS})
        set_property(TARGET Jasper::Jasper PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${Jasper_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT JPEG_FOUND)
            find_dependency(JPEG REQUIRED)
        else()
            message(STATUS "Dependency JPEG already found")
        endif()

    endif()
endif()
