#Ashley Tharp, Tyler Reed, Brian Quackenbush - Operating Systems - Project 1 - Fall 2013 

project1: main.cpp CPU.h CPU.cpp Memory.h Memory.cpp
	g++ main.cpp Memory.cpp CPU.cpp -o project1

clean:
	rm -rf *.o project1

